### PR TITLE
Add missing strictures

### PR DESCRIPTION
**Pull request by shlomif**
CPANTS Kwalitee.

### CODE REVIEW

**Comment by ribasushi** [comment]
@shlomif `FATAL => 'all'` prliferation is a generally bad idea and is [officially discouraged by p5p](https://metacpan.org/pod/distribution/perl/regen/warnings.pl#Fatal-Warnings). Please consider following up with a reversal PR.

**Comment by shlomif** [comment]
@ribasushi : hello! The «FATAL => 'all'» for the «use warnings;» lines exist in all other .pm source files in DBM-Deep, so I added it in the missing .pm as well for consistency. I realise it's a bad idea and avoid using it for my own code. Maybe you should file an issue for it for DBM-Deep.

**Comment by robkinyon** [comment]
@ribasushi - The official discouragement came *years* after I stopped actively working on DBM::Deep. I'd be happy to accept a PR that fixes the problem correctly (instead of just removing the `FATAL => 'all'`).

**Comment by ribasushi** [comment]
@robkinyon my comment wasn't a critique of the module as a whole, just of this PR. Blindly removing FATAL's without a code audit is just as dangerous as adding them where there were none (what this PR did). To put it in terms an engineer would understand:
- Adding crap to a structure without a containment tank is bad - god knows what it may contaminate
- Removing crap that has been there for years is equally bad - god knows what lifeform it actively supports

In any case - the original comment was simply made in passing, about something minor-ish I noticed. No action being taken is a perfectly reasonable outcome.

**Pull request merged**
